### ISSUE TITLE
Communication errors causing premature shutdown

### ISSUE THREAD

**Issue by mbainter** [Gamocosm/Gamocosm#123]
Lately we've been seeing some odd behavior.  I'm not certain but I think it's tied to these two errors that I see popping up in the server log:
<details>
<summary>Exception pinging Minecraft: end of file reached</summary>
<p>

```
 2020 Apr 15 (13:24:29 PDT)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00000000053300e0 @data=#<EOFError: end of file reached>, @msg="Exception pinging Minecraft: end of file reached">, #<Error:0x0000000005343118 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]
```

</p>
</details>
<details>
<summary>Exception pinging Minecraft: Unable to read: timeout</summary>
<p>

```
2020 Apr 15 (13:23:26 PDT)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000002cef598 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x0000000002d16058 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">] 
```

</details>

With automatic shutdown enabled, when this happens, it appears to assume that the server isn't in use, shuts it down and starts a snapshot process.

**Comment by Raekye** [comment]
Hmmm yeah that is possibly odd. I recently added support for the [Server List Ping](https://wiki.vg/Server_List_Ping) protocol, which I believe all (Java edition) servers should support since 1.7. Gamocosm now tries to use that first instead to get the player count. However, if that fails, it still tries to use the old query protocol, so in that sense, it should be fine

However, I also modified the old query protocol to use nonblocking IO instead of ruby's Timeout (see [here](https://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/) for an explanation why Timeout is dangerous. However, the message "Connection refused" is unrelated to a connection timing out AFAIK

Lastly, I believe the autoshutdown worker should not stop the server if it fails to ping/query. A quick glance at the code it seems that should be the case

How many times do you see these logs per start/stop of a server?

**Comment by mbainter** [comment]
Well - I just see them adjacent in the log, but that doesn't mean there's a causal connection necessarily.  I'll spin it up tomorrow and let it time out and see if I can get a clearer picture of what's happening.

**Comment by Raekye** [comment]
Ok looking over the code this morning, it seems [`autoshutdown_minecraft_worker.rb`](https://github.com/Gamocosm/Gamocosm/blob/a9b8de8fba9f4fefb2060b452c9516667d675278/app/workers/autoshutdown_minecraft_worker.rb) was quite buggy. In fact, with one of the issues, I'm actually not sure if/how it ever worked before

Anyways, two logical bugs have been fixed (hope I got it right now). Thanks for reporting this, and please let me know if you continue to have issues

**Comment by Raekye** [comment]
Ok, the old code didn't work the way it was probably intended to, but I see how it used to (coincidentally) work. There was still one super edge case bug, but I'm not sure if I actually fixed anything else

**Comment by mbainter** [comment]
Since things are more solid now I'm going to try to turn autoshutdown back on this week.  I'll report back soon on whether I see any further issues.
