### ISSUE TITLE
Duplicate droplets for the same server

### ISSUE THREAD

**Issue by unixfox** [Gamocosm/Gamocosm#138]
On the 4th of January one of my droplet didn't shut down and this happen twice. As a result of that I got two duplicate of my gamocosm server.

![image](https://user-images.githubusercontent.com/4016501/104631884-caa6a700-5694-11eb-85cb-871aede7ee08.png)

![image](https://user-images.githubusercontent.com/4016501/104631852-bebae500-5694-11eb-96b2-7b22f9719a42.png)

Here the logs between today and 4th January:
```
 2021 Jan 14 (06:51:44 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 14 (06:51:34 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 7 times)

2021 Jan 14 (06:12:59 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00000000039bbee8 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00000000039ba3b8 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 14 (06:11:21 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 14 (06:11:13 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 13 times)

2021 Jan 14 (04:46:47 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 14 (04:46:35 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 14 (04:27:05 PST)
app/workers/start_minecraft_worker.rb:23:in `perform'

Error starting Minecraft on server: MCSW API error: action start response status not OK, was minecraft_orphaned, {"pid"=>0, "status"=>"minecraft_orphaned"}

2021 Jan 14 (04:26:24 PST)
app/workers/setup_server_worker.rb:84:in `rescue in perform'

Server started, but connection refused while trying to SSH (attempt 1, Exception while executing as root@159.203.12.34: Connection refused - connect(2) for 159.203.12.34:4022). Trying again in 16 seconds

2021 Jan 14 (04:26:08 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 14 (04:26:01 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 15 times)

2021 Jan 14 (04:25:55 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 14 times)

2021 Jan 13 (21:05:17 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 13 (21:05:07 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 17 times)

2021 Jan 13 (11:17:55 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 13 (11:17:45 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 33 times)

2021 Jan 13 (11:17:22 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 13 (10:58:55 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000005d834e8 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007f90740b7730 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception querying Minecraft: Unable to read: timeout">]

2021 Jan 13 (03:26:54 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 13 (03:26:44 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 18 times)

2021 Jan 12 (18:56:36 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 12 (18:56:26 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 20 times)

2021 Jan 12 (15:01:34 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 12 (15:01:28 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 5 times)

2021 Jan 11 (10:39:14 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 11 (10:39:09 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 5 times)

2021 Jan 10 (11:13:31 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 10 (11:13:22 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 18 times)

2021 Jan 10 (08:00:24 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 10 (07:59:59 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 10 (01:33:06 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007fd5042ff888 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007fd5042fc868 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 9 (08:23:02 PST)
app/models/minecraft/node.rb:52:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2021 Jan 9 (06:54:40 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 9 (06:54:33 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 8 times)

2021 Jan 9 (02:55:00 PST)
app/workers/setup_server_worker.rb:84:in `rescue in perform'

Server started, but connection refused while trying to SSH (attempt 1, Exception while executing as root@165.22.226.177: Connection refused - connect(2) for 165.22.226.177:4022). Trying again in 16 seconds

2021 Jan 8 (16:08:25 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 8 (16:08:15 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 35 times)

2021 Jan 8 (16:07:43 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 8 (13:05:57 PST)
app/workers/setup_server_worker.rb:84:in `rescue in perform'

Server started, but connection refused while trying to SSH (attempt 1, Exception while executing as root@134.122.46.133: Connection refused - connect(2) for 134.122.46.133:4022). Trying again in 16 seconds

2021 Jan 8 (11:27:27 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 8 (11:27:15 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 17 times)

2021 Jan 8 (11:27:06 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 16 times)

2021 Jan 7 (17:58:04 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 7 (17:57:54 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 33 times)

2021 Jan 7 (17:57:43 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 7 (16:58:58 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007fee7039ad30 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007fee7039a308 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 6 (21:34:57 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 6 (21:34:52 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 4 times)

2021 Jan 6 (21:26:29 PST)
app/models/minecraft/node.rb:52:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2021 Jan 6 (21:14:28 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007f04a44c0720 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007f04a44dadc8 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception querying Minecraft: Unable to read: timeout">]

2021 Jan 6 (19:44:48 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 6 (19:44:40 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 6 times)

2021 Jan 6 (14:00:59 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 6 (14:00:49 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 36 times)

2021 Jan 6 (14:00:38 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 35 times)

2021 Jan 6 (14:00:06 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 6 (12:58:41 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 6 (12:58:34 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 13 times)

2021 Jan 6 (12:55:27 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 6 (12:55:13 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 6 (09:14:13 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000005621038 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x000000000562bee8 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 6 (09:12:34 PST)
app/workers/setup_server_worker.rb:84:in `rescue in perform'

Server started, but connection refused while trying to SSH (attempt 1, Exception while executing as root@167.99.181.222: Connection refused - connect(2) for 167.99.181.222:4022). Trying again in 16 seconds

2021 Jan 6 (09:12:11 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 6 (09:12:06 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 13 times)

2021 Jan 6 (08:58:49 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 6 (08:58:39 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 17 times)

2021 Jan 5 (20:47:18 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 5 (20:47:04 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 34 times)

2021 Jan 5 (20:46:37 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 5 (20:20:50 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000004288e40 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x0000000004288300 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (20:19:18 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 5 (20:19:10 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 11 times)

2021 Jan 5 (19:42:03 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 5 (19:41:51 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 5 (15:31:54 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007f71840cf808 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007f71840cec28 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (15:30:19 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 5 (15:30:13 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 14 times)

2021 Jan 5 (14:42:26 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 5 (14:42:06 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 5 (09:20:35 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00000000043fba98 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00000000043f9fb8 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (09:19:29 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007f7180425fb0 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007f71804256a0 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (09:18:24 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007f71802912f8 @data=#<Errno::ECONNREFUSED: Connection refused - connect(2) for 159.89.116.237:25565>, @msg="Exception pinging Minecraft: Connection refused - connect(2) for 159.89.116.237:25565">, #<Error:0x00007f7180290a38 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (09:16:48 PST)
app/workers/setup_server_worker.rb:89:in `rescue in perform'

Server started, but connection timed out while trying to SSH (attempt 1, Exception while executing as root@159.89.116.237: Net::SSH::ConnectionTimeout). Trying again in 16 seconds

2021 Jan 5 (09:16:43 PST)
app/models/minecraft/node.rb:52:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2021 Jan 5 (06:18:23 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000004009228 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x000000000400ff10 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (06:16:49 PST)
app/workers/setup_server_worker.rb:84:in `rescue in perform'

Server started, but connection refused while trying to SSH (attempt 1, Exception while executing as root@159.203.22.227: Connection refused - connect(2) for 159.203.22.227:4022). Trying again in 16 seconds

2021 Jan 5 (05:54:02 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 5 (05:53:27 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 5 (04:31:10 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000003712d90 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00000000037195a0 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (04:25:39 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 5 (04:25:25 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 34 times)

2021 Jan 5 (04:25:07 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 5 (04:19:05 PST)
app/models/minecraft/node.rb:52:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2021 Jan 5 (04:18:38 PST)
app/models/minecraft/node.rb:52:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: Net::ReadTimeout with #<TCPSocket:(closed)>

2021 Jan 5 (04:16:31 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x000000000171df58 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x000000000171cf40 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 5 (04:15:27 PST)
app/models/minecraft/node.rb:52:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: Net::ReadTimeout with #<TCPSocket:(closed)>

2021 Jan 5 (04:14:19 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000004256558 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00000000042557e8 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 4 (17:46:29 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 4 (17:46:16 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 32 times)

2021 Jan 4 (17:34:43 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x0000000003df5ab8 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x0000000003df5018 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 4 (17:33:07 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 4 (17:32:59 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 12 times)

2021 Jan 4 (15:37:34 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 4 (15:37:21 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 34 times)

2021 Jan 4 (15:36:55 PST)
app/workers/wait_for_snapshotting_server_worker.rb:40:in `perform'

Still waiting for Digital Ocean server to snapshot, tried 32 times

2021 Jan 4 (14:29:33 PST)
app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'

Could not query Minecraft: [#<Error:0x00007fc2c415f958 @data=#<NonblockIOTimeout: Unable to read: timeout>, @msg="Exception pinging Minecraft: Unable to read: timeout">, #<Error:0x00007fc2c415e6c0 @data=#<Errno::ECONNREFUSED: Connection refused>, @msg="Exception querying Minecraft: Connection refused">]

2021 Jan 4 (14:27:54 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 4 (14:27:46 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 13 times)

2021 Jan 4 (10:58:20 PST)
app/workers/wait_for_starting_server_worker.rb:25:in `perform'

Error with Digital Ocean start server action 1106774725; Digital Ocean API HTTP response status not ok: 404: {"id":"not_found","message":"The resource you were accessing could not be found."} . Aborting

2021 Jan 4 (07:17:18 PST)
app/workers/wait_for_starting_server_worker.rb:59:in `perform'

Server started successfully

2021 Jan 4 (07:17:11 PST)
app/workers/wait_for_starting_server_worker.rb:53:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 7 times)

2021 Jan 4 (07:16:26 PST)
app/workers/wait_for_starting_server_worker.rb:25:in `perform'

Error with Digital Ocean start server action 1106658888; Digital Ocean API HTTP response status not ok: 404: {"id":"not_found","message":"The resource you were accessing could not be found."} . Aborting

2021 Jan 4 (02:53:28 PST)
app/workers/wait_for_snapshotting_server_worker.rb:70:in `perform'

Finished snapshotting server on Digital Ocean and got snapshot ID

2021 Jan 4 (02:53:20 PST)
app/workers/wait_for_snapshotting_server_worker.rb:53:in `perform'

Finished snapshotting server on Digital Ocean, but unable to get latest snapshot id. Trying again (tried 18 times) 
```

Does someone know what happened?

**Comment by alexsapps** [comment]
I also had two droplets for the same server and even when my server wasn't supposedly running, the extra droplet was still left on and it racked up a bunch of charges for me on DigitalOcean.

In the Digital Ocean activity log, I saw this series of events:

added 8:25pm mysvr.minecraft.gamocosmcreated
added 8:25pm mysvr.minecraft.gamocosmcreated
created 8:26pm mysvr.minecraft.gamocosmadded
created 8:26pm mysvr.minecraft.gamocosmadded

I believe someone must have quickly double clicked the start button and Gamocosm didn't prevent multiple start requests from going through. Andd I tested this out just now by quickly hitting the start button several times in succession and it actually created 3 droplets. I'll file a separate issue.
