### ISSUE TITLE
Able to connect via IP address, but not domain name

### ISSUE THREAD

**Issue by ethnevar** [Gamocosm/Gamocosm#61]
Weird issue which applies to both connecting via Minecraft client and FTP. I can connect just fine if I use the IP address, but when I use the domain name nada. It's not a big deal, just a quality of life issue because the server IP is not static. 

Server log:

2016 Dec 2 (14:51:50 PST) app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'
Error querying Minecraft server
2016 Dec 2 (14:50:35 PST) app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'
Error querying Minecraft server
2016 Dec 2 (14:49:26 PST) app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'
Error querying Minecraft server
2016 Dec 2 (14:48:19 PST) app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'
Error querying Minecraft server
2016 Dec 2 (14:47:09 PST) app/workers/autoshutdown_minecraft_worker.rb:55:in `perform'
Error querying Minecraft server
2016 Dec 2 (14:42:55 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired

**Comment by ethnevar** [comment]
And... nevermind. It has resolved itself.
