### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by lukeguild** [Gamocosm/Gamocosm#81]
Hey Raekye,
Having some issues getting a new server set up:

MCSW is unable to connect to multiple droplets.

droplet 1 (initial setup on gamocosm, new DO account, new key)
```
2018 Apr 3 (19:48:45 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2018 Apr 3 (19:48:32 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (19:42:29 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (19:42:19 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2018 Apr 3 (19:32:17 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (19:32:00 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (19:31:48 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2018 Apr 3 (18:42:22 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:42:13 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:42:04 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:55 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:47 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:38 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:29 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:20 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:11 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:41:01 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:40:52 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:40:42 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.27.44" port 5000
2018 Apr 3 (18:40:33 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
```

second droplet (figured i'd shut it down and give it another try)
```
2018 Apr 3 (19:53:02 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.165.12" port 5000
2018 Apr 3 (19:52:44 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.131.165.12" port 5000
2018 Apr 3 (19:52:35 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
```

I can SSH into port 4022 just fine, but nothing's connecting to 5000 properly.

client also cant connect:
![image](https://user-images.githubusercontent.com/5841693/38286255-6e34d646-3792-11e8-9e8e-2ee1dc026580.png)

**Comment by lukeguild** [comment]
False alarm 👎 

The server startup script took an exceedingly long time to complete (like 25 min.)
Once the script completed it all sorted itself out and the connection on port 5000 is fine.

Maybe MCSW could wait for the server startup script to finish execution? I know thats not very maintainable with the endless variety of scripts you could end up having to handle.

Thanks for all your work Raekye, Gamocosm is a gem!
